// eslint.config.js — ESLint flat config (ESLint 9+ / Node 18+)
export default [
    {
        files: ['src/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                console: 'readonly',
                process: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                AbortController: 'readonly',
                performance: 'readonly',
                URL: 'readonly',
                Date: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Promise: 'readonly',
                Float64Array: 'readonly',
                JSON: 'readonly',
                Math: 'readonly',
                Infinity: 'readonly',
                isNaN: 'readonly',
                parseFloat: 'readonly',
                parseInt: 'readonly',
                String: 'readonly',
                Array: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-constant-condition': 'warn',
            'no-debugger': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty': ['warn', { allowEmptyCatch: true }],
            'no-redeclare': 'error',
            'no-unreachable': 'warn',
            'eqeqeq': ['warn', 'smart'],
            'no-var': 'error',
            'prefer-const': ['warn', { destructuring: 'all' }],
        },
    },
    {
        ignores: ['node_modules/', 'data/'],
    },
];
